In [1]:
import numpy as np
#task1: create array of id for each dept
Hr_id = np.arange(1,4)
IT_id = np.arange(4,19)
Fin_id = np.arange(19,24)
Sales_id = np.arange(24,31)
print(Hr_id)
print(IT_id)
print(Fin_id)
print(Sales_id)

[1 2 3]
[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[19 20 21 22 23]
[24 25 26 27 28 29 30]


In [3]:
#task2: array for salary of each dept
Hr_sal = np.array([50000,60000,57000])
It=[67000]
IT_sal = np.array(It*15)
Fin_sal = np.array([60000,65000,50000,70000,87000])
Sales_sal = np.array([50000,60000,65000,90000,56000,65000,71000])
print(Hr_sal)
print(IT_sal)
print(Fin_sal)
print(Sales_sal)


[50000 60000 57000]
[67000 67000 67000 67000 67000 67000 67000 67000 67000 67000 67000 67000
 67000 67000 67000]
[60000 65000 50000 70000 87000]
[50000 60000 65000 90000 56000 65000 71000]


In [5]:
#task3: department wise average salary & dept with highest average salary
avg_hr = round(np.mean(Hr_sal),2)
avg_IT = round(np.mean(IT_sal),2)
avg_Fin = round(np.mean(Fin_sal),2)
avg_sales = round(np.mean(Sales_sal),2)
print('The average salary in HR department:',avg_hr)
print('The average salary in IT department:',avg_IT)
print('The average salary in Finance department:',avg_Fin)
print('The average salary in Sales department:',avg_sales)
Total_avg=max(avg_hr,avg_IT,avg_Fin,avg_sales)
print('The highest average salary is',Total_avg,'for IT department')

The average salary in HR department: 55666.67
The average salary in IT department: 67000.0
The average salary in Finance department: 66400.0
The average salary in Sales department: 65285.71
The highest average salary is 67000.0 for IT department


In [7]:
#task4: highest salary in Hr and Finance dept
print('The highest salary in HR:',max(Hr_sal))
print('The highest salary in Finance:',max(Fin_sal))

The highest salary in HR: 60000
The highest salary in Finance: 87000


In [9]:
#task5: update bonus of 5% for IT dept
IT_sal = IT_sal + IT_sal*0.05
print('Updated salary:',IT_sal)

Updated salary: [70350. 70350. 70350. 70350. 70350. 70350. 70350. 70350. 70350. 70350.
 70350. 70350. 70350. 70350. 70350.]


University Admission decision

In [11]:
import numpy as np
from numpy import genfromtxt

In [13]:
#task1: import data into 2D file
adm_data = genfromtxt('DS1_C4_S1_AdmissionPredict_Data_Practice__1_.csv',delimiter=',',skip_header=1)
#print(adm_data)
print('The number of rows, columns are:',adm_data.shape)

The number of rows, columns are: (400, 9)


In [15]:
#task2: GRE score of all students
print('The GRE score of all students:\n',adm_data[0:,1:2])

The GRE score of all students:
 [[337.]
 [324.]
 [316.]
 [322.]
 [314.]
 [330.]
 [321.]
 [308.]
 [302.]
 [323.]
 [325.]
 [327.]
 [328.]
 [307.]
 [311.]
 [314.]
 [317.]
 [319.]
 [318.]
 [303.]
 [312.]
 [325.]
 [328.]
 [334.]
 [336.]
 [340.]
 [322.]
 [298.]
 [295.]
 [310.]
 [300.]
 [327.]
 [338.]
 [340.]
 [331.]
 [320.]
 [299.]
 [300.]
 [304.]
 [307.]
 [308.]
 [316.]
 [313.]
 [332.]
 [326.]
 [322.]
 [329.]
 [339.]
 [321.]
 [327.]
 [313.]
 [312.]
 [334.]
 [324.]
 [322.]
 [320.]
 [316.]
 [298.]
 [300.]
 [311.]
 [309.]
 [307.]
 [304.]
 [315.]
 [325.]
 [325.]
 [327.]
 [316.]
 [318.]
 [328.]
 [332.]
 [336.]
 [321.]
 [314.]
 [314.]
 [329.]
 [327.]
 [301.]
 [296.]
 [294.]
 [312.]
 [340.]
 [320.]
 [322.]
 [340.]
 [319.]
 [315.]
 [317.]
 [314.]
 [316.]
 [318.]
 [299.]
 [298.]
 [301.]
 [303.]
 [304.]
 [306.]
 [331.]
 [332.]
 [323.]
 [322.]
 [312.]
 [314.]
 [317.]
 [326.]
 [316.]
 [329.]
 [338.]
 [331.]
 [304.]
 [305.]
 [321.]
 [301.]
 [320.]
 [311.]
 [310.]
 [299.]
 [290.]
 [296.]
 [327.]
 [335.]


In [17]:
#task3: No of students whose GRE score above 320
index=np.where(adm_data[0:,1]>320)
index
gre_score=adm_data[index,1].size
print('The number of students who have GRE score above 320 is',gre_score)

The number of students who have GRE score above 320 is 163


In [19]:
#task4: Admission chance of students who have TOEFL above 110
index=np.where(adm_data[0:,2]>110)
index
toefl_score=100*adm_data[index,8]
print('The admission chance for students having TOEFL greater than 110 is:\n',toefl_score)

The admission chance for students having TOEFL greater than 110 is:
 [[92. 90. 84. 78. 70. 94. 95. 97. 94. 91. 90. 94. 87. 91. 86. 89. 78. 78.
  72. 52. 55. 61. 78. 94. 96. 93. 72. 74. 96. 92. 94. 86. 90. 79. 74. 87.
  91. 93. 94. 94. 85. 78. 84. 92. 96. 79. 89. 80. 90. 92. 97. 80. 81. 83.
  96. 93. 94. 86. 81. 89. 89. 87. 85. 90. 89. 93. 93. 88. 90. 86. 94. 97.
  97. 95. 96. 94. 93. 91. 76. 71. 82. 91. 88. 85. 86. 70. 76. 77. 93. 85.
  90. 70. 83. 89. 80. 94. 93. 92. 89. 86. 90. 71. 80. 79. 80. 81. 80. 80.
  83. 94. 93. 91. 86. 95. 96. 96. 84. 89. 91. 95.]]


In [21]:
#task5: scholarship of 1000, for students who has Toefl>115 & GRE > 315; Number of such eligible students & their serial number
index=np.where((adm_data[0:,1]>315) & (adm_data[0:,2]>115) & (adm_data[0:,7]>0))
index
scholarship=adm_data[index,0]
total_numb=adm_data[index,0].size
print('A total of',total_numb,'students are eligible for scholarship')
print('Serial number of those students are:\n',scholarship)

A total of 41 students are eligible for scholarship
Serial number of those students are:
 [[  1.  23.  24.  25.  26.  33.  53.  71.  82.  98.  99. 108. 109. 121.
  122. 130. 139. 142. 144. 149. 152. 172. 177. 188. 194. 203. 204. 213.
  214. 215. 216. 260. 286. 287. 326. 338. 362. 373. 386. 398. 400.]]
